//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace groupProject.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/Group_Project")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Item_DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Item_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Item_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Item_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Category {
            get {
                return this.Item_CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_CategoryField, value) != true)) {
                    this.Item_CategoryField = value;
                    this.RaisePropertyChanged("Item_Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Description {
            get {
                return this.Item_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_DescriptionField, value) != true)) {
                    this.Item_DescriptionField = value;
                    this.RaisePropertyChanged("Item_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Item_Discount {
            get {
                return this.Item_DiscountField;
            }
            set {
                if ((this.Item_DiscountField.Equals(value) != true)) {
                    this.Item_DiscountField = value;
                    this.RaisePropertyChanged("Item_Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item_Id {
            get {
                return this.Item_IdField;
            }
            set {
                if ((this.Item_IdField.Equals(value) != true)) {
                    this.Item_IdField = value;
                    this.RaisePropertyChanged("Item_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Image {
            get {
                return this.Item_ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_ImageField, value) != true)) {
                    this.Item_ImageField = value;
                    this.RaisePropertyChanged("Item_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Name {
            get {
                return this.Item_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_NameField, value) != true)) {
                    this.Item_NameField = value;
                    this.RaisePropertyChanged("Item_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Item_Price {
            get {
                return this.Item_PriceField;
            }
            set {
                if ((this.Item_PriceField.Equals(value) != true)) {
                    this.Item_PriceField = value;
                    this.RaisePropertyChanged("Item_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item_Quantity {
            get {
                return this.Item_QuantityField;
            }
            set {
                if ((this.Item_QuantityField.Equals(value) != true)) {
                    this.Item_QuantityField = value;
                    this.RaisePropertyChanged("Item_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Status {
            get {
                return this.Item_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_StatusField, value) != true)) {
                    this.Item_StatusField = value;
                    this.RaisePropertyChanged("Item_Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Group_Project")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItems", ReplyAction="http://tempuri.org/IService1/GetItemsResponse")]
        groupProject.ServiceReference1.Item[] GetItems(string cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItems", ReplyAction="http://tempuri.org/IService1/GetItemsResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetItemsAsync(string cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllItems", ReplyAction="http://tempuri.org/IService1/GetAllItemsResponse")]
        groupProject.ServiceReference1.Item[] GetAllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllItems", ReplyAction="http://tempuri.org/IService1/GetAllItemsResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetAllItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnSpecialCakes", ReplyAction="http://tempuri.org/IService1/GetOnSpecialCakesResponse")]
        groupProject.ServiceReference1.Item[] GetOnSpecialCakes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnSpecialCakes", ReplyAction="http://tempuri.org/IService1/GetOnSpecialCakesResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnSpecialCakesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnAnniversryCakes", ReplyAction="http://tempuri.org/IService1/GetOnAnniversryCakesResponse")]
        groupProject.ServiceReference1.Item[] GetOnAnniversryCakes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnAnniversryCakes", ReplyAction="http://tempuri.org/IService1/GetOnAnniversryCakesResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnAnniversryCakesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnBirthdayCakes", ReplyAction="http://tempuri.org/IService1/GetOnBirthdayCakesResponse")]
        groupProject.ServiceReference1.Item[] GetOnBirthdayCakes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnBirthdayCakes", ReplyAction="http://tempuri.org/IService1/GetOnBirthdayCakesResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnBirthdayCakesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnBuy1Cakes", ReplyAction="http://tempuri.org/IService1/GetOnBuy1CakesResponse")]
        groupProject.ServiceReference1.Item[] GetOnBuy1Cakes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnBuy1Cakes", ReplyAction="http://tempuri.org/IService1/GetOnBuy1CakesResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnBuy1CakesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFeatured", ReplyAction="http://tempuri.org/IService1/GetFeaturedResponse")]
        groupProject.ServiceReference1.Item[] GetFeatured();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFeatured", ReplyAction="http://tempuri.org/IService1/GetFeaturedResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetFeaturedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnPromotion", ReplyAction="http://tempuri.org/IService1/GetOnPromotionResponse")]
        groupProject.ServiceReference1.Item[] GetOnPromotion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnPromotion", ReplyAction="http://tempuri.org/IService1/GetOnPromotionResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnPromotionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnGraduation", ReplyAction="http://tempuri.org/IService1/GetOnGraduationResponse")]
        groupProject.ServiceReference1.Item[] GetOnGraduation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOnGraduation", ReplyAction="http://tempuri.org/IService1/GetOnGraduationResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnGraduationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalcDiscount", ReplyAction="http://tempuri.org/IService1/CalcDiscountResponse")]
        decimal CalcDiscount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalcDiscount", ReplyAction="http://tempuri.org/IService1/CalcDiscountResponse")]
        System.Threading.Tasks.Task<decimal> CalcDiscountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategory", ReplyAction="http://tempuri.org/IService1/GetCategoryResponse")]
        groupProject.ServiceReference1.Item[] GetCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategory", ReplyAction="http://tempuri.org/IService1/GetCategoryResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItem", ReplyAction="http://tempuri.org/IService1/GetItemResponse")]
        groupProject.ServiceReference1.Item GetItem(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetItem", ReplyAction="http://tempuri.org/IService1/GetItemResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.Item> GetItemAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        groupProject.ServiceReference1.User Login(string email, string passWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.User> LoginAsync(string email, string passWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegUser", ReplyAction="http://tempuri.org/IService1/RegUserResponse")]
        bool RegUser(string Name, string Email, string PassWord, string Address, string Phone, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegUser", ReplyAction="http://tempuri.org/IService1/RegUserResponse")]
        System.Threading.Tasks.Task<bool> RegUserAsync(string Name, string Email, string PassWord, string Address, string Phone, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUser", ReplyAction="http://tempuri.org/IService1/CheckUserResponse")]
        bool CheckUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUser", ReplyAction="http://tempuri.org/IService1/CheckUserResponse")]
        System.Threading.Tasks.Task<bool> CheckUserAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditUser", ReplyAction="http://tempuri.org/IService1/EditUserResponse")]
        bool EditUser(string Name, string Email, string PassWord, string Address, string Phone, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditUser", ReplyAction="http://tempuri.org/IService1/EditUserResponse")]
        System.Threading.Tasks.Task<bool> EditUserAsync(string Name, string Email, string PassWord, string Address, string Phone, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        groupProject.ServiceReference1.User getUser(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUser", ReplyAction="http://tempuri.org/IService1/getUserResponse")]
        System.Threading.Tasks.Task<groupProject.ServiceReference1.User> getUserAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : groupProject.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<groupProject.ServiceReference1.IService1>, groupProject.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public groupProject.ServiceReference1.Item[] GetItems(string cat) {
            return base.Channel.GetItems(cat);
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetItemsAsync(string cat) {
            return base.Channel.GetItemsAsync(cat);
        }
        
        public groupProject.ServiceReference1.Item[] GetAllItems() {
            return base.Channel.GetAllItems();
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetAllItemsAsync() {
            return base.Channel.GetAllItemsAsync();
        }
        
        public groupProject.ServiceReference1.Item[] GetOnSpecialCakes() {
            return base.Channel.GetOnSpecialCakes();
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnSpecialCakesAsync() {
            return base.Channel.GetOnSpecialCakesAsync();
        }
        
        public groupProject.ServiceReference1.Item[] GetOnAnniversryCakes() {
            return base.Channel.GetOnAnniversryCakes();
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnAnniversryCakesAsync() {
            return base.Channel.GetOnAnniversryCakesAsync();
        }
        
        public groupProject.ServiceReference1.Item[] GetOnBirthdayCakes() {
            return base.Channel.GetOnBirthdayCakes();
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnBirthdayCakesAsync() {
            return base.Channel.GetOnBirthdayCakesAsync();
        }
        
        public groupProject.ServiceReference1.Item[] GetOnBuy1Cakes() {
            return base.Channel.GetOnBuy1Cakes();
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnBuy1CakesAsync() {
            return base.Channel.GetOnBuy1CakesAsync();
        }
        
        public groupProject.ServiceReference1.Item[] GetFeatured() {
            return base.Channel.GetFeatured();
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetFeaturedAsync() {
            return base.Channel.GetFeaturedAsync();
        }
        
        public groupProject.ServiceReference1.Item[] GetOnPromotion() {
            return base.Channel.GetOnPromotion();
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnPromotionAsync() {
            return base.Channel.GetOnPromotionAsync();
        }
        
        public groupProject.ServiceReference1.Item[] GetOnGraduation() {
            return base.Channel.GetOnGraduation();
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetOnGraduationAsync() {
            return base.Channel.GetOnGraduationAsync();
        }
        
        public decimal CalcDiscount() {
            return base.Channel.CalcDiscount();
        }
        
        public System.Threading.Tasks.Task<decimal> CalcDiscountAsync() {
            return base.Channel.CalcDiscountAsync();
        }
        
        public groupProject.ServiceReference1.Item[] GetCategory() {
            return base.Channel.GetCategory();
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item[]> GetCategoryAsync() {
            return base.Channel.GetCategoryAsync();
        }
        
        public groupProject.ServiceReference1.Item GetItem(int Id) {
            return base.Channel.GetItem(Id);
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.Item> GetItemAsync(int Id) {
            return base.Channel.GetItemAsync(Id);
        }
        
        public groupProject.ServiceReference1.User Login(string email, string passWord) {
            return base.Channel.Login(email, passWord);
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.User> LoginAsync(string email, string passWord) {
            return base.Channel.LoginAsync(email, passWord);
        }
        
        public bool RegUser(string Name, string Email, string PassWord, string Address, string Phone, string type) {
            return base.Channel.RegUser(Name, Email, PassWord, Address, Phone, type);
        }
        
        public System.Threading.Tasks.Task<bool> RegUserAsync(string Name, string Email, string PassWord, string Address, string Phone, string type) {
            return base.Channel.RegUserAsync(Name, Email, PassWord, Address, Phone, type);
        }
        
        public bool CheckUser(string email) {
            return base.Channel.CheckUser(email);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserAsync(string email) {
            return base.Channel.CheckUserAsync(email);
        }
        
        public bool EditUser(string Name, string Email, string PassWord, string Address, string Phone, string type) {
            return base.Channel.EditUser(Name, Email, PassWord, Address, Phone, type);
        }
        
        public System.Threading.Tasks.Task<bool> EditUserAsync(string Name, string Email, string PassWord, string Address, string Phone, string type) {
            return base.Channel.EditUserAsync(Name, Email, PassWord, Address, Phone, type);
        }
        
        public groupProject.ServiceReference1.User getUser(int Id) {
            return base.Channel.getUser(Id);
        }
        
        public System.Threading.Tasks.Task<groupProject.ServiceReference1.User> getUserAsync(int Id) {
            return base.Channel.getUserAsync(Id);
        }
    }
}
